Show error message

diff --git a/.azure-pipelines/step-mirror.yml b/.azure-pipelines/step-mirror.yml
--- a/.azure-pipelines/step-mirror.yml
+++ b/.azure-pipelines/step-mirror.yml
@@ -11,7 +11,11 @@ steps:
 - script: |
     EXIT_CODE=0
     # On every error signal, set EXIT_CODE to -1 but keep running.
-    trap "EXIT_CODE=-1" ERR
+    function on_error() {
+      EXIT_CODE=-1
+      echo "\##vso[task.logissue type=error]Failed to sync $TARGET"
+    }
+    trap on_error ERR
 
     # Echo error if github-pat is empty
     [ -z $(github-pat) ] && echo "github-pat is empty!" && exit -1
@@ -45,8 +49,7 @@ steps:
       git checkout --detach source_branch 2> /dev/null && git branch -D source_branch || true
       # Checkout source_branch
       git checkout -b source_branch source/$SOURCE_BRANCH || {
-        echo "Branch $SOURCE_BRANCH not exist on $SOURCE_REPO"
-        EXIT_CODE=2
+        echo "Branch $SOURCE_BRANCH not exist on $SOURCE_REPO" && on_error
         continue
       }
 
@@ -82,8 +85,7 @@ steps:
         }
         # Rebase to reserve customized commits in target repo.
         git rebase --strategy-option=theirs refs/heads/source_branch || {
-          echo "Failed to rebase!" >&2
-          EXIT_CODE=2
+          echo "Failed to rebase!" >&2 && on_error
           git status
           git diff
           git rebase --abort
